adjective1 = input("Enter an adjective: ")
noun = input("Enter a noun: ")
adjective2 = input ("Enter an adjective: ")
verb = input("Enter a verb: ")
adjective3 = input("Enter another adjective: ")

print(f"Today I travelled to {adjective1}")
print(f"When I got there I saw {noun}")
print(f"{noun} was {adjective2} and {verb}ing")
print(f"I was {adjective3}")